package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CoachAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAllPropertiesEquals(Coach expected, Coach actual) {
        assertCoachAutoGeneratedPropertiesEquals(expected, actual);
        assertCoachAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAllUpdatablePropertiesEquals(Coach expected, Coach actual) {
        assertCoachUpdatableFieldsEquals(expected, actual);
        assertCoachUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachAutoGeneratedPropertiesEquals(Coach expected, Coach actual) {
        assertThat(actual)
            .as("Verify Coach auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachUpdatableFieldsEquals(Coach expected, Coach actual) {
        assertThat(actual)
            .as("Verify Coach relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getCognome()).as("check cognome").isEqualTo(expected.getCognome()))
            .satisfies(a -> assertThat(a.getItsMe()).as("check itsMe").isEqualTo(expected.getItsMe()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCoachUpdatableRelationshipsEquals(Coach expected, Coach actual) {
        assertThat(actual)
            .as("Verify Coach relationships")
            .satisfies(a -> assertThat(a.getSquadra()).as("check squadra").isEqualTo(expected.getSquadra()));
    }
}
