package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GiocatoreAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGiocatoreAllPropertiesEquals(Giocatore expected, Giocatore actual) {
        assertGiocatoreAutoGeneratedPropertiesEquals(expected, actual);
        assertGiocatoreAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGiocatoreAllUpdatablePropertiesEquals(Giocatore expected, Giocatore actual) {
        assertGiocatoreUpdatableFieldsEquals(expected, actual);
        assertGiocatoreUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGiocatoreAutoGeneratedPropertiesEquals(Giocatore expected, Giocatore actual) {
        assertThat(actual)
            .as("Verify Giocatore auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGiocatoreUpdatableFieldsEquals(Giocatore expected, Giocatore actual) {
        assertThat(actual)
            .as("Verify Giocatore relevant properties")
            .satisfies(a -> assertThat(a.getPlayer()).as("check player").isEqualTo(expected.getPlayer()))
            .satisfies(a -> assertThat(a.getTeam()).as("check team").isEqualTo(expected.getTeam()))
            .satisfies(a -> assertThat(a.getSeason()).as("check season").isEqualTo(expected.getSeason()))
            .satisfies(a -> assertThat(a.getAge()).as("check age").isEqualTo(expected.getAge()))
            .satisfies(a -> assertThat(a.getSquad()).as("check squad").isEqualTo(expected.getSquad()))
            .satisfies(a -> assertThat(a.getComp()).as("check comp").isEqualTo(expected.getComp()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getMp()).as("check mp").isEqualTo(expected.getMp()))
            .satisfies(a -> assertThat(a.getStarts()).as("check starts").isEqualTo(expected.getStarts()))
            .satisfies(a -> assertThat(a.getStartsPct()).as("check startsPct").isEqualTo(expected.getStartsPct()))
            .satisfies(a -> assertThat(a.getMinutes()).as("check minutes").isEqualTo(expected.getMinutes()))
            .satisfies(a -> assertThat(a.getNins()).as("check nins").isEqualTo(expected.getNins()))
            .satisfies(a -> assertThat(a.getGls()).as("check gls").isEqualTo(expected.getGls()))
            .satisfies(a -> assertThat(a.getAst()).as("check ast").isEqualTo(expected.getAst()))
            .satisfies(a -> assertThat(a.getgPlusA()).as("check gPlusA").isEqualTo(expected.getgPlusA()))
            .satisfies(a -> assertThat(a.getgPk()).as("check gPk").isEqualTo(expected.getgPk()))
            .satisfies(a -> assertThat(a.getPk()).as("check pk").isEqualTo(expected.getPk()))
            .satisfies(a -> assertThat(a.getPkatt()).as("check pkatt").isEqualTo(expected.getPkatt()))
            .satisfies(a -> assertThat(a.getCrdy()).as("check crdy").isEqualTo(expected.getCrdy()))
            .satisfies(a -> assertThat(a.getCrdr()).as("check crdr").isEqualTo(expected.getCrdr()))
            .satisfies(a -> assertThat(a.getXg()).as("check xg").isEqualTo(expected.getXg()))
            .satisfies(a -> assertThat(a.getXag()).as("check xag").isEqualTo(expected.getXag()))
            .satisfies(a -> assertThat(a.getNpxg()).as("check npxg").isEqualTo(expected.getNpxg()))
            .satisfies(a -> assertThat(a.getXgPlusXag()).as("check xgPlusXag").isEqualTo(expected.getXgPlusXag()))
            .satisfies(a -> assertThat(a.getNpxgPlusXag()).as("check npxgPlusXag").isEqualTo(expected.getNpxgPlusXag()))
            .satisfies(a -> assertThat(a.getPrgp()).as("check prgp").isEqualTo(expected.getPrgp()))
            .satisfies(a -> assertThat(a.getPrgc()).as("check prgc").isEqualTo(expected.getPrgc()))
            .satisfies(a -> assertThat(a.getPrgr()).as("check prgr").isEqualTo(expected.getPrgr()))
            .satisfies(a -> assertThat(a.getGlsPer90()).as("check glsPer90").isEqualTo(expected.getGlsPer90()))
            .satisfies(a -> assertThat(a.getAstPer90()).as("check astPer90").isEqualTo(expected.getAstPer90()))
            .satisfies(a -> assertThat(a.getgPlusAPer90()).as("check gPlusAPer90").isEqualTo(expected.getgPlusAPer90()))
            .satisfies(a -> assertThat(a.getXgPer90()).as("check xgPer90").isEqualTo(expected.getXgPer90()))
            .satisfies(a -> assertThat(a.getXagPer90()).as("check xagPer90").isEqualTo(expected.getXagPer90()))
            .satisfies(a -> assertThat(a.getXgPlusXagPer90()).as("check xgPlusXagPer90").isEqualTo(expected.getXgPlusXagPer90()))
            .satisfies(a -> assertThat(a.getXgDiff()).as("check xgDiff").isEqualTo(expected.getXgDiff()))
            .satisfies(a -> assertThat(a.getXaDiff()).as("check xaDiff").isEqualTo(expected.getXaDiff()))
            .satisfies(a -> assertThat(a.getTrend()).as("check trend").isEqualTo(expected.getTrend()))
            .satisfies(a -> assertThat(a.getNewleague()).as("check newleague").isEqualTo(expected.getNewleague()))
            .satisfies(a -> assertThat(a.getSourcefile()).as("check sourcefile").isEqualTo(expected.getSourcefile()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getCareerMp()).as("check careerMp").isEqualTo(expected.getCareerMp()))
            .satisfies(a -> assertThat(a.getCareerStarts()).as("check careerStarts").isEqualTo(expected.getCareerStarts()))
            .satisfies(a -> assertThat(a.getCareerMin()).as("check careerMin").isEqualTo(expected.getCareerMin()))
            .satisfies(a -> assertThat(a.getCareer90s()).as("check career90s").isEqualTo(expected.getCareer90s()))
            .satisfies(a -> assertThat(a.getCareerGls()).as("check careerGls").isEqualTo(expected.getCareerGls()))
            .satisfies(a -> assertThat(a.getCareerAst()).as("check careerAst").isEqualTo(expected.getCareerAst()))
            .satisfies(a -> assertThat(a.getCareerGPlusA()).as("check careerGPlusA").isEqualTo(expected.getCareerGPlusA()))
            .satisfies(a -> assertThat(a.getCareerXg()).as("check careerXg").isEqualTo(expected.getCareerXg()))
            .satisfies(a -> assertThat(a.getCareerXag()).as("check careerXag").isEqualTo(expected.getCareerXag()))
            .satisfies(a -> assertThat(a.getCareerXgPlusXag()).as("check careerXgPlusXag").isEqualTo(expected.getCareerXgPlusXag()))
            .satisfies(a -> assertThat(a.getCareerNpxg()).as("check careerNpxg").isEqualTo(expected.getCareerNpxg()))
            .satisfies(a -> assertThat(a.getCareerNpxgPlusXag()).as("check careerNpxgPlusXag").isEqualTo(expected.getCareerNpxgPlusXag()))
            .satisfies(a -> assertThat(a.getCareerGlsPer90()).as("check careerGlsPer90").isEqualTo(expected.getCareerGlsPer90()))
            .satisfies(a -> assertThat(a.getCareerAstPer90()).as("check careerAstPer90").isEqualTo(expected.getCareerAstPer90()))
            .satisfies(a -> assertThat(a.getCareerGPlusAPer90()).as("check careerGPlusAPer90").isEqualTo(expected.getCareerGPlusAPer90()))
            .satisfies(a -> assertThat(a.getCareerXgPer90()).as("check careerXgPer90").isEqualTo(expected.getCareerXgPer90()))
            .satisfies(a -> assertThat(a.getCareerXagPer90()).as("check careerXagPer90").isEqualTo(expected.getCareerXagPer90()))
            .satisfies(a ->
                assertThat(a.getCareerXgPlusXagPer90()).as("check careerXgPlusXagPer90").isEqualTo(expected.getCareerXgPlusXagPer90())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGiocatoreUpdatableRelationshipsEquals(Giocatore expected, Giocatore actual) {
        assertThat(actual)
            .as("Verify Giocatore relationships")
            .satisfies(a -> assertThat(a.getSquadra()).as("check squadra").isEqualTo(expected.getSquadra()))
            .satisfies(a -> assertThat(a.getWatchList()).as("check watchList").isEqualTo(expected.getWatchList()));
    }
}
