package it.costantino.astaapp.domain;

import java.util.Random;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicLong;

public class GiocatoreTestSamples {

    private static final Random random = new Random();
    private static final AtomicLong longCount = new AtomicLong(random.nextInt() + (2 * Integer.MAX_VALUE));

    public static Giocatore getGiocatoreSample1() {
        return new Giocatore()
            .id(1L)
            .player("player1")
            .team("team1")
            .season("season1")
            .age("age1")
            .squad("squad1")
            .comp("comp1")
            .country("country1")
            .mp(1L)
            .starts(1L)
            .startsPct(1L)
            .minutes(1L)
            .nins(1L)
            .gls(1L)
            .ast(1L)
            .gPlusA(1L)
            .gPk(1L)
            .pk(1L)
            .pkatt(1L)
            .crdy(1L)
            .crdr(1L)
            .xg(1L)
            .xag(1L)
            .npxg(1L)
            .xgPlusXag(1L)
            .npxgPlusXag(1L)
            .prgp(1L)
            .prgc(1L)
            .prgr(1L)
            .glsPer90(1L)
            .astPer90(1L)
            .gPlusAPer90(1L)
            .xgPer90(1L)
            .xagPer90(1L)
            .xgPlusXagPer90(1L)
            .xgDiff(1L)
            .xaDiff(1L)
            .trend("trend1")
            .newleague("newleague1")
            .sourcefile("sourcefile1")
            .careerMp(1L)
            .careerStarts(1L)
            .careerMin(1L)
            .career90s(1L)
            .careerGls(1L)
            .careerAst(1L)
            .careerGPlusA(1L)
            .careerXg(1L)
            .careerXag(1L)
            .careerXgPlusXag(1L)
            .careerNpxg(1L)
            .careerNpxgPlusXag(1L)
            .careerGlsPer90(1L)
            .careerAstPer90(1L)
            .careerGPlusAPer90(1L)
            .careerXgPer90(1L)
            .careerXagPer90(1L)
            .careerXgPlusXagPer90(1L);
    }

    public static Giocatore getGiocatoreSample2() {
        return new Giocatore()
            .id(2L)
            .player("player2")
            .team("team2")
            .season("season2")
            .age("age2")
            .squad("squad2")
            .comp("comp2")
            .country("country2")
            .mp(2L)
            .starts(2L)
            .startsPct(2L)
            .minutes(2L)
            .nins(2L)
            .gls(2L)
            .ast(2L)
            .gPlusA(2L)
            .gPk(2L)
            .pk(2L)
            .pkatt(2L)
            .crdy(2L)
            .crdr(2L)
            .xg(2L)
            .xag(2L)
            .npxg(2L)
            .xgPlusXag(2L)
            .npxgPlusXag(2L)
            .prgp(2L)
            .prgc(2L)
            .prgr(2L)
            .glsPer90(2L)
            .astPer90(2L)
            .gPlusAPer90(2L)
            .xgPer90(2L)
            .xagPer90(2L)
            .xgPlusXagPer90(2L)
            .xgDiff(2L)
            .xaDiff(2L)
            .trend("trend2")
            .newleague("newleague2")
            .sourcefile("sourcefile2")
            .careerMp(2L)
            .careerStarts(2L)
            .careerMin(2L)
            .career90s(2L)
            .careerGls(2L)
            .careerAst(2L)
            .careerGPlusA(2L)
            .careerXg(2L)
            .careerXag(2L)
            .careerXgPlusXag(2L)
            .careerNpxg(2L)
            .careerNpxgPlusXag(2L)
            .careerGlsPer90(2L)
            .careerAstPer90(2L)
            .careerGPlusAPer90(2L)
            .careerXgPer90(2L)
            .careerXagPer90(2L)
            .careerXgPlusXagPer90(2L);
    }

    public static Giocatore getGiocatoreRandomSampleGenerator() {
        return new Giocatore()
            .id(longCount.incrementAndGet())
            .player(UUID.randomUUID().toString())
            .team(UUID.randomUUID().toString())
            .season(UUID.randomUUID().toString())
            .age(UUID.randomUUID().toString())
            .squad(UUID.randomUUID().toString())
            .comp(UUID.randomUUID().toString())
            .country(UUID.randomUUID().toString())
            .mp(longCount.incrementAndGet())
            .starts(longCount.incrementAndGet())
            .startsPct(longCount.incrementAndGet())
            .minutes(longCount.incrementAndGet())
            .nins(longCount.incrementAndGet())
            .gls(longCount.incrementAndGet())
            .ast(longCount.incrementAndGet())
            .gPlusA(longCount.incrementAndGet())
            .gPk(longCount.incrementAndGet())
            .pk(longCount.incrementAndGet())
            .pkatt(longCount.incrementAndGet())
            .crdy(longCount.incrementAndGet())
            .crdr(longCount.incrementAndGet())
            .xg(longCount.incrementAndGet())
            .xag(longCount.incrementAndGet())
            .npxg(longCount.incrementAndGet())
            .xgPlusXag(longCount.incrementAndGet())
            .npxgPlusXag(longCount.incrementAndGet())
            .prgp(longCount.incrementAndGet())
            .prgc(longCount.incrementAndGet())
            .prgr(longCount.incrementAndGet())
            .glsPer90(longCount.incrementAndGet())
            .astPer90(longCount.incrementAndGet())
            .gPlusAPer90(longCount.incrementAndGet())
            .xgPer90(longCount.incrementAndGet())
            .xagPer90(longCount.incrementAndGet())
            .xgPlusXagPer90(longCount.incrementAndGet())
            .xgDiff(longCount.incrementAndGet())
            .xaDiff(longCount.incrementAndGet())
            .trend(UUID.randomUUID().toString())
            .newleague(UUID.randomUUID().toString())
            .sourcefile(UUID.randomUUID().toString())
            .careerMp(longCount.incrementAndGet())
            .careerStarts(longCount.incrementAndGet())
            .careerMin(longCount.incrementAndGet())
            .career90s(longCount.incrementAndGet())
            .careerGls(longCount.incrementAndGet())
            .careerAst(longCount.incrementAndGet())
            .careerGPlusA(longCount.incrementAndGet())
            .careerXg(longCount.incrementAndGet())
            .careerXag(longCount.incrementAndGet())
            .careerXgPlusXag(longCount.incrementAndGet())
            .careerNpxg(longCount.incrementAndGet())
            .careerNpxgPlusXag(longCount.incrementAndGet())
            .careerGlsPer90(longCount.incrementAndGet())
            .careerAstPer90(longCount.incrementAndGet())
            .careerGPlusAPer90(longCount.incrementAndGet())
            .careerXgPer90(longCount.incrementAndGet())
            .careerXagPer90(longCount.incrementAndGet())
            .careerXgPlusXagPer90(longCount.incrementAndGet());
    }
}
