package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LegaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegaAllPropertiesEquals(Lega expected, Lega actual) {
        assertLegaAutoGeneratedPropertiesEquals(expected, actual);
        assertLegaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegaAllUpdatablePropertiesEquals(Lega expected, Lega actual) {
        assertLegaUpdatableFieldsEquals(expected, actual);
        assertLegaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegaAutoGeneratedPropertiesEquals(Lega expected, Lega actual) {
        assertThat(actual)
            .as("Verify Lega auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegaUpdatableFieldsEquals(Lega expected, Lega actual) {
        assertThat(actual)
            .as("Verify Lega relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()))
            .satisfies(a -> assertThat(a.getBudget()).as("check budget").isEqualTo(expected.getBudget()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLegaUpdatableRelationshipsEquals(Lega expected, Lega actual) {
        assertThat(actual)
            .as("Verify Lega relationships")
            .satisfies(a -> assertThat(a.getStagione()).as("check stagione").isEqualTo(expected.getStagione()));
    }
}
