package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RosterAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAllPropertiesEquals(Roster expected, Roster actual) {
        assertRosterAutoGeneratedPropertiesEquals(expected, actual);
        assertRosterAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAllUpdatablePropertiesEquals(Roster expected, Roster actual) {
        assertRosterUpdatableFieldsEquals(expected, actual);
        assertRosterUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterAutoGeneratedPropertiesEquals(Roster expected, Roster actual) {
        assertThat(actual)
            .as("Verify Roster auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterUpdatableFieldsEquals(Roster expected, Roster actual) {
        assertThat(actual)
            .as("Verify Roster relevant properties")
            .satisfies(a -> assertThat(a.getFull()).as("check full").isEqualTo(expected.getFull()))
            .satisfies(a -> assertThat(a.getPort()).as("check port").isEqualTo(expected.getPort()))
            .satisfies(a -> assertThat(a.getDif()).as("check dif").isEqualTo(expected.getDif()))
            .satisfies(a -> assertThat(a.getCc()).as("check cc").isEqualTo(expected.getCc()))
            .satisfies(a -> assertThat(a.getAtt()).as("check att").isEqualTo(expected.getAtt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRosterUpdatableRelationshipsEquals(Roster expected, Roster actual) {
        assertThat(actual)
            .as("Verify Roster relationships")
            .satisfies(a -> assertThat(a.getSquadra()).as("check squadra").isEqualTo(expected.getSquadra()));
    }
}
