package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SquadraAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSquadraAllPropertiesEquals(Squadra expected, Squadra actual) {
        assertSquadraAutoGeneratedPropertiesEquals(expected, actual);
        assertSquadraAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSquadraAllUpdatablePropertiesEquals(Squadra expected, Squadra actual) {
        assertSquadraUpdatableFieldsEquals(expected, actual);
        assertSquadraUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSquadraAutoGeneratedPropertiesEquals(Squadra expected, Squadra actual) {
        assertThat(actual)
            .as("Verify Squadra auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSquadraUpdatableFieldsEquals(Squadra expected, Squadra actual) {
        assertThat(actual)
            .as("Verify Squadra relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSquadraUpdatableRelationshipsEquals(Squadra expected, Squadra actual) {
        assertThat(actual)
            .as("Verify Squadra relationships")
            .satisfies(a -> assertThat(a.getLega()).as("check lega").isEqualTo(expected.getLega()));
    }
}
