package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StagioneAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStagioneAllPropertiesEquals(Stagione expected, Stagione actual) {
        assertStagioneAutoGeneratedPropertiesEquals(expected, actual);
        assertStagioneAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStagioneAllUpdatablePropertiesEquals(Stagione expected, Stagione actual) {
        assertStagioneUpdatableFieldsEquals(expected, actual);
        assertStagioneUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStagioneAutoGeneratedPropertiesEquals(Stagione expected, Stagione actual) {
        assertThat(actual)
            .as("Verify Stagione auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStagioneUpdatableFieldsEquals(Stagione expected, Stagione actual) {
        assertThat(actual)
            .as("Verify Stagione relevant properties")
            .satisfies(a -> assertThat(a.getNome()).as("check nome").isEqualTo(expected.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStagioneUpdatableRelationshipsEquals(Stagione expected, Stagione actual) {
        // empty method
    }
}
