package it.costantino.astaapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WatchListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAllPropertiesEquals(WatchList expected, WatchList actual) {
        assertWatchListAutoGeneratedPropertiesEquals(expected, actual);
        assertWatchListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAllUpdatablePropertiesEquals(WatchList expected, WatchList actual) {
        assertWatchListUpdatableFieldsEquals(expected, actual);
        assertWatchListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListAutoGeneratedPropertiesEquals(WatchList expected, WatchList actual) {
        assertThat(actual)
            .as("Verify WatchList auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListUpdatableFieldsEquals(WatchList expected, WatchList actual) {
        assertThat(actual)
            .as("Verify WatchList relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()))
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWatchListUpdatableRelationshipsEquals(WatchList expected, WatchList actual) {
        assertThat(actual)
            .as("Verify WatchList relationships")
            .satisfies(a -> assertThat(a.getSquadra()).as("check squadra").isEqualTo(expected.getSquadra()));
    }
}
