import { ISquadra } from 'app/shared/model/squadra.model';
import { IWatchList } from 'app/shared/model/watch-list.model';
import { Role } from 'app/shared/model/enumerations/role.model';

export interface IGiocatore {
  id?: number;
  player?: string | null;
  team?: string | null;
  season?: string | null;
  age?: string | null;
  squad?: string | null;
  comp?: string | null;
  country?: string | null;
  mp?: number | null;
  starts?: number | null;
  startsPct?: number | null;
  minutes?: number | null;
  nins?: number | null;
  gls?: number | null;
  ast?: number | null;
  gPlusA?: number | null;
  gPk?: number | null;
  pk?: number | null;
  pkatt?: number | null;
  crdy?: number | null;
  crdr?: number | null;
  xg?: number | null;
  xag?: number | null;
  npxg?: number | null;
  xgPlusXag?: number | null;
  npxgPlusXag?: number | null;
  prgp?: number | null;
  prgc?: number | null;
  prgr?: number | null;
  glsPer90?: number | null;
  astPer90?: number | null;
  gPlusAPer90?: number | null;
  xgPer90?: number | null;
  xagPer90?: number | null;
  xgPlusXagPer90?: number | null;
  xgDiff?: number | null;
  xaDiff?: number | null;
  trend?: string | null;
  newleague?: string | null;
  sourcefile?: string | null;
  role?: keyof typeof Role | null;
  careerMp?: number | null;
  careerStarts?: number | null;
  careerMin?: number | null;
  career90s?: number | null;
  careerGls?: number | null;
  careerAst?: number | null;
  careerGPlusA?: number | null;
  careerXg?: number | null;
  careerXag?: number | null;
  careerXgPlusXag?: number | null;
  careerNpxg?: number | null;
  careerNpxgPlusXag?: number | null;
  careerGlsPer90?: number | null;
  careerAstPer90?: number | null;
  careerGPlusAPer90?: number | null;
  careerXgPer90?: number | null;
  careerXagPer90?: number | null;
  careerXgPlusXagPer90?: number | null;
  squadra?: ISquadra | null;
  watchList?: IWatchList | null;
}

export const defaultValue: Readonly<IGiocatore> = {};
